name: Deploy Traefik

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Traefik via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            envs: ACME_EMAIL=${{ secrets.ACME_EMAIL }}
            script: |
                mkdir -p /home/debian/traefik
                rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./docker-compose.yml debian@${{ secrets.HOST }}:/home/debian/traefik/
                ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} debian@${{ secrets.HOST }} "cd /home/debian/traefik && docker-compose up -d"
    
